[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    non-go = false